## Anagram

In [1]:
def anagram(s1,s2):
    s1=s1.replace(" ","").lower
    s2=s2.replace(" ",'').lower
    return sorted('s1')==sorted('s2')

In [2]:
anagram('god','dog')

False

## Tranvese the Array

In [3]:
arr1=[1,2,3,4,5,6,7,8,9]

def transArray(array):
    for i in array:
        print(i)
        
transArray(arr1)

1
2
3
4
5
6
7
8
9


## Acessing the element of array

In [4]:
arr1=[1,2,3,4,5,6,7,8,9]

In [5]:
def accessElement(array,index):
    if index>len(array):
        print("There is not any element in this index")
    else:
        print(array[index])

In [6]:
accessElement(arr1,4)

5


In [7]:
def searchAray(array,value):
    for i in array:
        if i==value:
            return array.index(value)
    return "Element not present in array "

In [8]:
searchAray(arr1,6)

5

In [9]:
arr1.remove(7)
print(arr1)

[1, 2, 3, 4, 5, 6, 8, 9]


## Creating 2D Array

In [10]:
import numpy as np

In [11]:
twoDArray= np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
twoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

## Insertion - Two Dimensional array

In [12]:
newTwoDArray=np.insert(twoDArray,0,[[1,2,3,4]],axis=1)
newTwoDArray

array([[ 1, 11, 15, 10,  6],
       [ 2, 10, 14, 11,  5],
       [ 3, 12, 17, 12,  8],
       [ 4, 15, 18, 14,  9]])

In [13]:
newTwoDArray=np.insert(twoDArray,0,[[1,2,3,4]],axis=0)
newTwoDArray

array([[ 1,  2,  3,  4],
       [11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

## Acessing Element

In [14]:
def accessElements(array,rowIndex,colIndex):
    if rowIndex >=len(array) and colIndex>=len(array[0]):
        print("Inccorect Index")
    else:
        print(array[rowIndex][colIndex])

In [15]:
accessElements(newTwoDArray,3,3)

8


## Traverse the Array

In [16]:
def travserse2DArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

In [17]:
travserse2DArray(twoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


## Searching for an element in 2D Array

In [18]:
def searcharr(array,value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j]==value:
                return "The is value is located at :" +str(i) +" at i position and "+ str(j) +" at j position"
    return ("The value in not in the Array: ")

In [19]:
searcharr(twoDArray,17)

'The is value is located at :2 at i position and 1 at j position'

In [20]:
searcharr(twoDArray,300)

'The value in not in the Array: '